import { type Ficha, STAT_LABELS, PV_BASE } from "../schema/fichaSchema";
import { exigeTitulo } from "../data/clasesSociales";

// Reconstruye la ficha en el formato exacto de la plantilla del grupo de WhatsApp.
export function generarTextoWhatsApp(f: Ficha): string {
  const e = f.estadisticas;
  const lineas: string[] = [];

  lineas.push("*╭═════°•>☾<•°═════╮*");
  lineas.push("                *º𝔗𝔥𝔢 ƙ𝔦𝔫𝔤𝔇𝔬𝔬𝔪t*");
  lineas.push("*╰═════°•>☾<•°═════╯*");
  lineas.push("");
  lineas.push("⊷⊶⊷•⊰❂⊱•⊷⊶⊷⊶⊷");
  lineas.push(`*-Nombre Completo/ Apodo:* ${f.nombre}`);
  lineas.push("");
  lineas.push(" ⊶⊰❂⊱⊶⊷⊶");
  lineas.push(`*-Edad:* ${f.edad}`);
  lineas.push("");
  lineas.push("⊶•⊰❂⊱•⊷⊶");
  lineas.push(`*-Genero:* ${f.genero}`);
  lineas.push("");
  lineas.push("⊶⊷•⊰❂⊱•⊷");
  lineas.push(`*-Estatura:* ${f.estatura}`);
  lineas.push("");
  lineas.push("⊶⊰❂⊱•⊶");
  lineas.push(`*-Raza:* ${f.raza}`);
  lineas.push("");
  lineas.push(" ⊶⊷⊶⊷⊶•⊰❂⊱•⊷⊶");
  lineas.push("*-Poderes Oficiales:*");
  lineas.push(f.poderesOficiales.trim());
  lineas.push("");
  lineas.push("⊶⊷⊶⊷⊶•⊰❂⊱•⊷⊶");
  lineas.push("*Estadsiticas:*");
  lineas.push("*Tienes 12 puntos para distribuir*");
  lineas.push("");
  lineas.push(`${STAT_LABELS.fuerza}: ${e.fuerza}`);
  lineas.push(`${STAT_LABELS.agilidad}: ${e.agilidad}`);
  lineas.push(`${STAT_LABELS.inteligencia}: ${e.inteligencia}`);
  lineas.push(`${STAT_LABELS.defensa}: ${e.defensa}`);
  lineas.push(`${STAT_LABELS.defensaMagica}: ${e.defensaMagica}`);
  lineas.push(`*Pv Base ${PV_BASE}*`);
  lineas.push("");
  lineas.push("");
  lineas.push("⊷⊶⊷⊷⊷•⊰❂⊱•⊷⊷⊷");
  lineas.push(`*-Arma principal* ${f.armaPrincipal}`);
  lineas.push("");
  lineas.push(`*-Estilo de combate* ${f.estiloCombate}`);
  lineas.push("");
  lineas.push("⊷⊶⊷⊷⊷•⊰❂⊱•⊷⊷⊷");
  lineas.push(`*-Reino donde nacio:* ${f.reino}`);
  lineas.push("");
  lineas.push("⊶⊷⊶⊷•⊰❂⊱•⊶⊷⊶⊷⊶⊷");
  lineas.push(`*-Clase social:* ${f.claseSocial}`);
  lineas.push("*(Noble, plebeyo o burgues u otro)*");
  lineas.push("");
  lineas.push("⊶⊷•⊰❂⊱•⊷⊶⊷⊶⊷");
  lineas.push(`*-Titulo de Nobleza:* ${exigeTitulo(f.claseSocial) ? f.tituloNobleza : ""}`);
  lineas.push("*(En caso de ser)*");
  lineas.push("");
  lineas.push("⊶⊷•⊰❂⊱•⊷");
  lineas.push(`*-Profesion:* ${f.profesion}`);
  lineas.push("");
  lineas.push("⊷⊶⊷⊶•⊰❂⊱•⊷⊶⊷⊶⊷⊶⊷");
  lineas.push("*-Habilidades no magicas:*");
  lineas.push(f.habilidadesNoMagicas.trim());
  lineas.push("");
  lineas.push("⊷⊶•⊰❂⊱•⊶⊷⊶");
  lineas.push("*-Personalidad:*");
  lineas.push(f.personalidad.trim());
  lineas.push("");
  lineas.push("⊶⊷•⊰❂⊱•⊶");
  lineas.push("*-Historia:*");
  lineas.push(f.historia.trim());
  lineas.push("");
  lineas.push("⊷•⊰❂⊱•⊶");
  lineas.push("*-Extras:*");
  lineas.push(f.extras.trim());
  lineas.push("");
  lineas.push("⊶⊷•⊰❂⊱•⊷⊶");
  lineas.push("*-Debilidades:*");
  lineas.push(f.debilidades.trim());
  lineas.push("");
  lineas.push("⊷•⊰❂⊱•⊶⊷⊶");
  lineas.push("*-Inventario:*");
  lineas.push(f.inventario.trim());
  lineas.push("");
  lineas.push("⊷⊶⊷⊶⊷⊶•⊰❂⊱•⊶⊷");
  lineas.push("*-Imagen/Descripción:*");
  lineas.push(f.imagenDescripcion.trim());

  return lineas.join("\n");
}
